# Generated by Django 4.2.2 on 2024-04-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default=False, upload_to='imagenes/'),
        ),
    ]
